[package]
name = "ping_oracle"
version = "0.1.0"
authors = ["tunv3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
oracle = "0.3.0"